# Generated by Django 6.0.3 on 2026-08-07 01:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_tokens(apps, schema_editor):
    """
    Sur Postgres, AddField avec un default callable (uuid.uuid4) et unique=True en
    une seule étape utilise LA MÊME valeur pour toutes les lignes existantes — d'où
    le UniqueViolation. On ajoute donc le champ nullable, on génère un token distinct
    par ligne ici, puis une migration suivante impose unique=True/null=False.
    """
    Document = apps.get_model('msi', 'Document')
    for document in Document.objects.all():
        document.token = uuid.uuid4()
        document.save(update_fields=['token'])


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0005_depense_sous_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='categorie',
            field=models.CharField(blank=True, choices=[('developpement', 'Développement de logiciel'), ('maintenance', 'Maintenance'), ('fonctionnalite', 'Ajout de fonctionnalité')], max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='date_reponse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='token',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(backfill_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='document',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('payee', 'Payée')], default='brouillon', max_length=20),
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('categorie', models.CharField(choices=[('developpement', 'Développement de logiciel'), ('maintenance', 'Maintenance'), ('fonctionnalite', 'Ajout de fonctionnalité')], max_length=20)),
                ('client_nom', models.CharField(max_length=200)),
                ('client_courriel', models.EmailField(max_length=254)),
                ('lignes_json', models.JSONField(default=list)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_tps', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_tvq', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('conditions_json', models.JSONField(default=list)),
                ('nom_signataire', models.CharField(max_length=200)),
                ('courriel_signataire', models.EmailField(max_length=254)),
                ('ip_signature', models.GenericIPAddressField()),
                ('user_agent_signature', models.CharField(blank=True, max_length=500)),
                ('date_signature', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(upload_to='contrats/')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('annule', 'Annulé')], default='actif', max_length=10)),
                ('soumission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contrat', to='msi.document')),
            ],
            options={
                'ordering': ['-date_signature'],
            },
        ),
    ]
