# Generated by Django 6.0.3 on 2026-08-07 01:33

import msi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0006_document_categorie_document_date_reponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='pdf',
            field=models.FileField(storage=msi.models.StockagePriveContrats(), upload_to='contrats/'),
        ),
    ]
