# Generated by Django 6.0.3 on 2026-08-07 14:56

import msi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0007_alter_contrat_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportComptableArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('trimestre', models.PositiveSmallIntegerField()),
                ('pdf', models.FileField(storage=msi.models.StockagePriveContrats(), upload_to='rapports-comptables/')),
                ('date_generation', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-annee', '-trimestre'],
                'constraints': [models.UniqueConstraint(fields=('annee', 'trimestre'), name='rapport_unique_par_periode')],
            },
        ),
    ]
