# Generated by Django 6.0.3 on 2026-08-23 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0010_rapportcomptablearchive_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='pourcentage_acompte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='contrat_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_liees', to='msi.contrat'),
        ),
        migrations.AddField(
            model_name='document',
            name='pourcentage_acompte',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Pourcentage d'acompte exigé à la signature (ex. 35). Laisser vide pour un paiement complet.", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='type_paiement',
            field=models.CharField(choices=[('complet', 'Complet'), ('acompte', 'Acompte'), ('solde', 'Solde')], default='complet', max_length=10),
        ),
    ]
