# Generated by Django 6.0.3 on 2026-08-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0011_contrat_pourcentage_acompte_document_contrat_lie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='signature_image',
            field=models.TextField(blank=True),
        ),
    ]
