# Generated by Django 6.0.3 on 2026-08-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0012_contrat_signature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='categorie',
            field=models.CharField(choices=[('developpement', 'Développement de logiciel'), ('maintenance', 'Maintenance'), ('fonctionnalite', 'Ajout de fonctionnalité'), ('abonnement_saas', 'Abonnement SaaS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='categorie',
            field=models.CharField(blank=True, choices=[('developpement', 'Développement de logiciel'), ('maintenance', 'Maintenance'), ('fonctionnalite', 'Ajout de fonctionnalité'), ('abonnement_saas', 'Abonnement SaaS')], max_length=20),
        ),
    ]
