# Generated by Django 6.1.1 on 2026-09-27 17:57

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def reprendre_factures_payees(apps, schema_editor):
    """
    Avant cette migration, une facture « payée » n'avait aucun paiement enregistré. On crée
    un paiement unique du montant total, daté du jour de la facture, pour que son solde dû
    reste à 0 $ et que le revenu déjà affiché ne change pas.
    """
    Document = apps.get_model('msi', 'Document')
    Paiement = apps.get_model('msi', 'Paiement')
    tps = Decimal(str(settings.TPS_RATE))
    tvq = Decimal(str(settings.TVQ_RATE))
    cent = Decimal('0.01')
    for facture in Document.objects.filter(type_document='facture', statut='payee').prefetch_related('lignes'):
        sous_total = sum(
            ((l.quantite * l.prix_unitaire).quantize(cent) for l in facture.lignes.all()), Decimal('0'),
        ).quantize(cent)
        total = sous_total + (sous_total * tps).quantize(cent) + (sous_total * tvq).quantize(cent)
        if total > 0:
            Paiement.objects.create(
                document=facture,
                date=facture.date_creation.date(),
                montant=total,
                mode='autre',
                note='Paiement repris automatiquement (facture déjà marquée payée).',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0014_articlecatalogue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_derniere_relance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='categorie',
            field=models.CharField(choices=[('developpement', 'Développement de logiciel'), ('maintenance', 'Maintenance'), ('fonctionnalite', 'Ajout de fonctionnalité'), ('abonnement_saas', 'Abonnement annuel ExtincPro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='categorie',
            field=models.CharField(blank=True, choices=[('developpement', 'Développement de logiciel'), ('maintenance', 'Maintenance'), ('fonctionnalite', 'Ajout de fonctionnalité'), ('abonnement_saas', 'Abonnement annuel ExtincPro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('partielle', 'Partiellement payée'), ('payee', 'Payée')], default='brouillon', max_length=20),
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='msi.document')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('virement', 'Virement Interac'), ('depot', 'Dépôt direct'), ('cheque', 'Chèque'), ('carte', 'Carte de crédit'), ('comptant', 'Comptant'), ('autre', 'Autre')], default='virement', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='N° de chèque, de transaction, etc.', max_length=100)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='msi.document')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.RunPython(reprendre_factures_payees, migrations.RunPython.noop),
    ]
