# Generated by Django 6.1.1 on 2026-09-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0015_paiements_echeancier'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='echeancier_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
