# Generated by Django 6.1.1 on 2026-09-27 20:28

import msi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0016_contrat_echeancier'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='preuve',
            field=models.FileField(blank=True, storage=msi.models.StockagePriveContrats(), upload_to='paiements/'),
        ),
    ]
