# Generated by Django 6.1.1 on 2026-09-27 20:34

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def marquer_existants(apps, schema_editor):
    """
    Les documents déjà en circulation avant l'arrivée des rappels automatiques sont marqués
    comme « déjà rappelés » : sinon le tout premier passage enverrait d'un coup des relances
    pour de vieilles soumissions et des rappels de retard pour des factures peut-être déjà
    payées mais jamais marquées. Les factures en retard recevront leur premier rappel
    automatique seulement après l'intervalle (7 jours par défaut) — le temps de faire le ménage.
    """
    Document = apps.get_model('msi', 'Document')
    Echeance = apps.get_model('msi', 'Echeance')
    # Daté de la veille : ces marques ne sont pas de vrais envois, elles ne doivent pas être
    # comptées dans « rappels envoyés aujourd'hui » du tableau de bord.
    maintenant = timezone.now() - timedelta(days=1)
    Document.objects.filter(type_document='soumission', statut='envoyee').update(
        date_relance_soumission=maintenant,
        date_rappel_expiration=maintenant,
        date_alerte_expiration=maintenant,
    )
    factures = Document.objects.filter(type_document='facture', statut__in=['envoyee', 'partielle'])
    factures.filter(date_derniere_relance__isnull=True).update(date_derniere_relance=maintenant)
    factures.update(date_rappel_avant_echeance=maintenant)
    Echeance.objects.filter(
        document__type_document='facture', document__statut__in=['envoyee', 'partielle'],
    ).update(date_rappel_avant=maintenant)


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0017_paiement_preuve'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordonnees',
            name='rappel_avant_versement_jours',
            field=models.PositiveSmallIntegerField(default=3, help_text='Rappeler un versement X jours avant sa date (0 = jamais).'),
        ),
        migrations.AddField(
            model_name='coordonnees',
            name='rappel_expiration_jours',
            field=models.PositiveSmallIntegerField(default=3, help_text="Prévenir le client X jours avant l'expiration de la soumission (0 = jamais)."),
        ),
        migrations.AddField(
            model_name='coordonnees',
            name='rappel_retard_intervalle_jours',
            field=models.PositiveSmallIntegerField(default=7, help_text='Relancer un paiement en retard au plus une fois tous les X jours (0 = jamais).'),
        ),
        migrations.AddField(
            model_name='coordonnees',
            name='rappels_actifs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coordonnees',
            name='relance_soumission_jours',
            field=models.PositiveSmallIntegerField(default=7, help_text='Relancer une soumission sans réponse X jours après son envoi (0 = jamais).'),
        ),
        migrations.AddField(
            model_name='document',
            name='date_alerte_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='date_envoi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='date_rappel_avant_echeance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='date_rappel_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='date_relance_soumission',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echeance',
            name='date_rappel_avant',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(marquer_existants, migrations.RunPython.noop),
    ]
